apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  namespace: expense
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log;
    pid /run/nginx.pid;

    # Load dynamic modules. See /usr/share/doc/nginx/README.dynamic.
    include /usr/share/nginx/modules/*.conf;

    events {
        worker_connections 1024;
    }

    http {
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile            on;
        tcp_nopush          on;
        tcp_nodelay         on;
        keepalive_timeout   65;
        types_hash_max_size 2048;

        include             /etc/nginx/mime.types;
        default_type        application/octet-stream;

        # Load modular configuration files from the /etc/nginx/conf.d directory.
        # See http://nginx.org/en/docs/ngx_core_module.html#include
        # for more information.
        include /etc/nginx/conf.d/*.conf;

        server {
            listen       8080 default_server;
            listen       [::]:8080 default_server;
            server_name  _;
            root         /usr/share/nginx/html;

            # Load configuration files for the default server block.
            include /etc/nginx/default.d/*.conf;

            location /api/ {
                proxy_pass http://backend:8080/;
                  # we are using host network mode in docker compose so we can use localhost to connect backend
                  # proxy_pass http://localhost:8080/;
                  # using host is not recommended for production use cases
            }
          
          
            error_page 404 /404.html;
                location = /40x.html {
            }

            error_page 500 502 503 504 /50x.html;
                location = /50x.html {
            }
        }

    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  # Labels for the deployment
  labels:
    app: frontend
    tier: web
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      tier: web
      project: expense
  # Pod template
  template:
    metadata:
      labels:
        app: frontend
        tier: web
        project: expense
    spec:
      # mount the configmap as volume
      volumes:
        - name: nginx-config
          configMap:
            name: nginx
            items:
              - key: nginx.conf
      containers:
        - name: nginx
          image: joindevops/frontend:1.0.0
          ports:
            - containerPort: 8080
          # mount the config file
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
---
# this will be internal only, we use ClusterIP. we need not to expose it outside
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
    tier: web
    project: expense
  ports:
    - protocol: TCP
      port: 8080 # Service Port
      targetPort: 8080 # Container Port
  type: ClusterIP
