apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  # Labels for the deployment
  labels:
    app: backend
    tier: backend
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: backend
      project: expense
  # Pod template
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        project: expense
    spec:
      containers:
        - name: backend
          image: joindevops/backend:1.0.0
          # environment variables from ConfigMap
          envFrom:
            - configMapRef:
                name: backend
---
# this will be internal only, we use ClusterIP. we need not to expose it outside
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
    tier: backend
    project: expense
  ports:
    - protocol: TCP
      port: 8080 # Service Port
      targetPort: 8080 # Container Port
  type: ClusterIP
